### ISSUE TITLE
bug(secret hitler): presidential legislative power npe

### ISSUE THREAD

**Issue by pikulet** [UltiMafia/Ultimafia#1001]
```
2023-08-09T00:47:59.958Z error: Cannot read property 'init' of undefined 
TypeError: Cannot read property 'init' of undefined
    at SecretHitlerGame.instantMeeting (/home/ec2-user/um/Games/core/Game.js:1395:14)
    at Action.run [as unboundRun] (/home/ec2-user/um/Games/types/Secret Hitler/items/PresidentialLegislativePower.js:24:23)
    at Action.do (/home/ec2-user/um/Games/core/Action.js:20:10)
    at SecretHitlerGame.instantAction (/home/ec2-user/um/Games/core/Game.js:1376:14)
    at Liberal.act (/home/ec2-user/um/Games/core/Role.js:355:17)
    at SecretHitlerPlayer.act (/home/ec2-user/um/Games/core/Player.js:742:30)
    at SecretHitlerMeeting.finish (/home/ec2-user/um/Games/core/Meeting.js:760:11)
```

**Comment by pikulet** [comment]
caused by #970
