### ISSUE TITLE
bug(mafia): check length of undefined

### ISSUE THREAD

**Issue by pikulet** [UltiMafia/Ultimafia#1098]
```
2023-08-27T19:14:32.778Z error: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at CultLeader.check (/home/ec2-user/um/Games/types/Mafia/roles/cards/WinWithCult.js:46:66)
    at MafiaGame.checkWinConditions (/home/ec2-user/um/Games/types/Mafia/Game.js:280:27)
```

**Comment by pikulet** [comment]
#1102
