### ISSUE TITLE
bug(game): adjusting colours gets textcolor of undefined

### ISSUE THREAD

**Issue by pikulet** [UltiMafia/Ultimafia#1174]
```
2023-09-09T15:48:57.193Z error: Cannot read property 'textColor' of undefined 
TypeError: Cannot read property 'textColor' of undefined
    at Message.getMessageInfo (/home/ec2-user/um/Games/core/Message.js:106:40)
    at /home/ec2-user/um/Games/core/PregameMeeting.js:21:13
```

**Comment by pikulet** [comment]
might be related to #1179
