### ISSUE TITLE
bug(quoting): unable to read from meeting id

### ISSUE THREAD

**Issue by pikulet** [UltiMafia/Ultimafia#408]
```
2023-06-23T00:59:47.765Z error: Cannot read property 'fromMeetingId' of undefined 
TypeError: Cannot read property 'fromMeetingId' of undefined
    at MafiaPlayer.speakQuote (/home/ec2-user/um/Games/types/Mafia/Player.js:120:13)
    at Quote.send (/home/ec2-user/um/Games/core/Quote.js:25:36)
    at VillageMeeting.quote (/home/ec2-user/um/Games/core/Meeting.js:797:11)
    at ServerSocket.<anonymous> (/home/ec2-user/um/Games/core/Player.js:174:17
```

not sure who tried to quote when

**Comment by pikulet** [comment]
maybe pregame?

**Comment by pikulet** [comment]
This error log appeared 3 times today.

**Comment by pikulet** [comment]
happens when thulued/ quote cancelled
