### ISSUE TITLE
bug(mafia): guiser error logs

### ISSUE THREAD

**Issue by pikulet** [UltiMafia/Ultimafia#698]
```
2023-07-17T22:13:24.636Z error: Cannot read property 'getImmunity' of undefined
TypeError: Cannot read property 'getImmunity' of undefined
    at MafiaAction.dominates (/home/ec2-user/um/Games/core/Action.js:31:29)
    at MafiaAction.run [as unboundRun] (/home/ec2-user/um/Games/types/Mafia/roles/cards/IdentityStealer.js:26:65)
    at MafiaAction.do (/home/ec2-user/um/Games/core/Action.js:20:10)
    at MafiaGame.processActionQueue (/home/ec2-user/um/Games/core/Game.js:1326:50)
```

**Comment by pikulet** [comment]
this means the mafia kill did not get a target, not able to reproduce without more information
