### ISSUE TITLE
bug(secret hitler): assassination seems broken

### ISSUE THREAD

**Issue by DrSharky** [UltiMafia/Ultimafia#723]
Got a React error after 4 fascist polices were enacted, and I think it happened when someone tried to do an assassination action.

Error in console, although it's a minified error, so I'm not sure how much help it will be:
```Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&amp;args[]=na for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
 at react-dom.production.min.js:149:359
 at Pi (react-dom.production.min.js:173:103)
 at mu (react-dom.production.min.js:262:428)
 at sc (react-dom.production.min.js:246:265)
 at uc (react-dom.production.min.js:246:194)
 at Zu (react-dom.production.min.js:239:172)
 at react-dom.production.min.js:123:115
 at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
 at Ha (react-dom.production.min.js:122:325)
 at $a (react-dom.production.min.js:123:61)
  | overrideMethod | @ | console.js:213
-- | -- | -- | --
  | eu | @ | react-dom.production.min.js:209
  | n.callback | @ | react-dom.production.min.js:226
  | fo | @ | react-dom.production.min.js:131
  | ou | @ | react-dom.production.min.js:212
  | dc | @ | react-dom.production.min.js:255
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Ha | @ | react-dom.production.min.js:122
  | pc | @ | react-dom.production.min.js:248
  | Zu | @ | react-dom.production.min.js:239
  | (anonymous) | @ | react-dom.production.min.js:123
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Ha | @ | react-dom.production.min.js:122
  | $a | @ | react-dom.production.min.js:123
  | qa | @ | react-dom.production.min.js:122
  | Gu | @ | react-dom.production.min.js:230
  | vi | @ | react-dom.production.min.js:163
  | (anonymous) | @ | Game.jsx:322
  | value | @ | Socket.js:45
  | (anonymous) | @ | Socket.js:35

**Comment by pikulet** [comment]
I made some fixes to secret hitler 7p+ games and special election
