### ISSUE TITLE
bug(mafia): butterfly error game crashed

### ISSUE THREAD

**Issue by pikulet** [UltiMafia/Ultimafia#827]
```
2023-07-29T00:25:47.133Z error: Cannot read property 'Shwartz99' of undefined 
TypeError: Cannot read property 'Shwartz99' of undefined
    at Butterfly.death (/home/ec2-user/um/Games/types/Mafia/roles/cards/ResetRolesOnDeath.js:14:52)
    at EventEmitter.emit (events.js:327:22)
    at MafiaPlayer.kill (/home/ec2-user/um/Games/core/Player.js:949:22)
    at MafiaPlayer.kill (/home/ec2-user/um/Games/types/Mafia/Player.js:76:11)
    at MafiaAction.run [as unboundRun] (/home/ec2-user/um/Games/types/Mafia/roles/cards/VillageCore.js:22:47)
    at MafiaAction.do (/home/ec2-user/um/Games/core/Action.js:20:10)
```

**Comment by pikulet** [comment]
https://ultimafia.com/learn/setup/UZHUmnEnd

this was the setup
